name: Swift

on:
  release:
    types: [created]

env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.POD_TOKEN }}

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Cocoapods lint
      run: pod trunk push PianoAnalytics.podspec
    - name: Cocoapods lint app extensions
      run: pod trunk push PianoAnalytics-AppExtension.podspec
